name: habitos
description: "Habit tracking app with offline-first architecture and Firebase sync"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Icons
  cupertino_icons: ^1.0.8
  
  # Firebase (Native SDK)
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  
  # State Management
  provider: ^6.1.0
  
  # Navigation
  go_router: ^13.0.0
  
  # Local Storage
  shared_preferences: ^2.2.0
  sqflite: ^2.3.0
  path: ^1.8.0
  
  # UI/UX
  flutter_local_notifications: ^16.2.0
  local_auth: ^2.1.0
  
  # Charts & Analytics
  fl_chart: ^0.65.0
  table_calendar: ^3.0.9
  
  # Utilities
  intl: ^0.18.0
  path_provider: ^2.1.0
  google_generative_ai: ^0.1.0
  connectivity_plus: ^5.0.0
  uuid: ^4.2.0
  
  # HTTP & Network
  http: ^1.1.0
  
  # Icons & Images
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.0

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/icons/
  
  # App Icons Configuration
flutter_launcher_icons:
  android: false  # iOS only
  ios: true
  image_path: "assets/icon.png"
  remove_alpha_ios: true
